apiVersion: apps/v1
kind: Deployment
metadata:
 name: meudeployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: peso
 template:
  metadata:
   labels:
    app: peso
  spec:
   containers:
   - name: web
     image: danilo/desafio-dotnet
     ports:
     - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: web
spec:
 selector:
  app: peso
 ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30000
 type: NodePort
